
nothread thread_attr_demo thread_demo : nothread.c thread_attr_demo.c thread_demo.c
	gcc -o nothread nothread.c -lpthread
	gcc -o thread_attr_demo thread_attr_demo.c -lpthread
	gcc -o thread_demo thread_demo.c -lpthread

clean:
	rm -f nothread thread_attr_demo thread_demo

