
assignment_1 signalsemmeprblm signalsemmesol : assignment_1.c signalsemmeprblm.c signalsemmesol.c	
	gcc -o assignment_1 assignment_1.c -lpthread
	gcc -o signalsemmeprblm  signalsemmeprblm.c -lpthread
	gcc -o signalsemmesol signalsemmesol.c -lpthread

clean:
	rm -rf assignment_1 signalsemmeprblm signalsemmesol