
recursiveprblm recursivesol : recursiveprblm.c recursivesol.c
	gcc -o recursiveprblm recursiveprblm.c -lpthread
	gcc -o recursivesol recursivesol.c -lpthread

clean :
	rm -rf recursiveprblm recursivesol	